### ISSUE TITLE
"You do not have permission to view this directory or page"

### ISSUE THREAD

**Issue by kayeew** [NZMSA/2019-Phase-1#1]
Anyone else also getting "You do not have permission to view this directory or page" error when deploying the how-old web app to Azure? The web app works fine locally, not sure where's the problem?

**Comment by hd910** [comment]
Hey @kayeew, few things I would try
- Have a look into the logs in Deployment Center to see if deployment was successful
- Make sure the stack is set to Node.js (you can check by going into Settings -> Configuration -> General Settings -> Stack)
- Check that a build and node modules folders were created by going to https://YOUR_WEB_APP_NAME.scm.azurewebsites.net/wwwroot/

As an alternate way to deploy, you can run `npm run build` locally and upload the contents of the build folder to Azure

**Comment by kayeew** [comment]
> 
> 
> Hey @kayeew, few things I would try
> 
>     * Have a look into the logs in Deployment Center to see if deployment was successful
> 
>     * Make sure the stack is set to Node.js (you can check by going into Settings -> Configuration -> General Settings -> Stack)
> 
>     * Check that a build and node modules folders were created by going to https://YOUR_WEB_APP_NAME.scm.azurewebsites.net/wwwroot/
> 
> 
> As an alternate way to deploy, you can run `npm run build` locally and upload the contents of the build folder to Azure

Hey @hd910, I see, my stack settings was actually set to .NET but NodeJS not on the list.
![image](https://user-images.githubusercontent.com/42571166/56121309-f5496480-5fc3-11e9-8f96-77f985aeebc6.png)

**Comment by hd910** [comment]
Hey @kayeew, that interface looks quite different to the one I'm seeing... could you upload the full screenshot of the app resource? (something like this)

<img width="1137" alt="Screen Shot 2019-04-15 at 9 32 07 PM" src="https://user-images.githubusercontent.com/9142110/56122236-0b582480-5fc6-11e9-978e-75ee8168efba.png">

**Comment by kayeew** [comment]
My interface is the same, just the NodeJS option is not on the stack list.
![image](https://user-images.githubusercontent.com/42571166/56122734-2aa38180-5fc7-11e9-8e9f-b93173b28b17.png)
![image](https://user-images.githubusercontent.com/42571166/56122773-44dd5f80-5fc7-11e9-816a-227b24acbcfd.png)

**Comment by hd910** [comment]
@kayeew Is it also the case when you create a new web app? 

<img width="1024" alt="Screen Shot 2019-04-15 at 9 51 56 PM" src="https://user-images.githubusercontent.com/9142110/56123526-bec21880-5fc8-11e9-87ae-d19f26e6fdca.png">

**Comment by kayeew** [comment]
@hd910, theres no runtime stack field on my interface, just Application Insights.
![image](https://user-images.githubusercontent.com/42571166/56123766-460f8c00-5fc9-11e9-9924-d480c83950bf.png)

**Comment by hd910** [comment]
@kayeew I see you're on the Free Trial subscription. Could you try registering for [Azure for Students](https://github.com/NZMSA/2019-Phase-1/tree/master/Azure%20For%20Students) and try creating the resource again?

**Comment by kayeew** [comment]
@hd910, apparently it says I'm not eligible for the  Azure for Students subscription, even though I have verified my school using my student mail.
![image](https://user-images.githubusercontent.com/42571166/56124479-d5696f00-5fca-11e9-9c4c-7c7f9c6ada0d.png)

**Comment by hd910** [comment]
@kayeew we have had issues with loading up this subscription to existing Uni Azure accounts in the past. Could you try with a non-university account (e.g. outlook)?

**Comment by kayeew** [comment]
@hd910 I've managed to get the student subscription with my non uni email but the create web app interface is still the same:
![image](https://user-images.githubusercontent.com/42571166/56126172-ace37400-5fce-11e9-9e20-1ea984ba587d.png)

**Comment by hd910** [comment]
Hey @kayeew please try changing the OS to Linus

**Comment by kayeew** [comment]
Thanks @hd910, I've got it working.
