### ISSUE TITLE
Web App - Failed to deploy on Microsoft Azure

### ISSUE THREAD

**Issue by kyzh0** [NZMSA/2019-Phase-1#3]
I've followed the video and guide step-by-step for the "How Old" web app, but it fails to deploy on Azure. I'm using the free student version.
![Log](https://user-images.githubusercontent.com/49678883/56325632-ff878080-61c6-11e9-9f54-cadaf61416ef.png)

**Comment by hd910** [comment]
Hey @kyzh0, could you try setting the stack setting to Node.js? (you can check by going into Settings -> Configuration -> General Settings -> Stack)

Also have a look at this [closed issue](https://github.com/NZMSA/2019-Phase-1/issues/1)

**Comment by kyzh0** [comment]
Thank you, I didn't realise it was the same problem from the title.
