### ISSUE TITLE
Azure deployment for how-old web app

### ISSUE THREAD

**Issue by cecilia-yin** [NZMSA/2019-Phase-1#6]
I followed every step from the instruction and my code works in VS code. However, when I try to deploy to Azure, it always fails. I have taken a screenshot of my logs, could someone pls explain to me what went wrong.

![Screen Shot 2019-07-04 at 10 00 49 AM](https://user-images.githubusercontent.com/41213946/60631649-cfee2900-9e43-11e9-8139-85d2006432d3.png)

**Comment by margeobur** [comment]
Have a look at the package.json that's in the root folder of your project. If it doesn't have an entry under dependencies for react-loader-spinner, then open your project folder in a terminal, run "npm i react-loader-spinner".
Commit and push, and it should redeploy.
- on my phone so sorry if this lacks detail

**Comment by cecilia-yin** [comment]
Thanks, it worked.
